services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\DoctrineEntityCheckerBundle\Checker\:
    resource: '../../Checker/'
  Tourze\DoctrineEntityCheckerBundle\Service\:
    resource: '../../Service/'
    public: true # 防止测试用例中把这些服务删除了

  Yiisoft\Strings\Inflector: ~
